/** Generated by scripts/detectAssets.ts: where the worker's downloads are, and how big. */
declare module 'virtual:detect-assets' {
  /** The pinned Pyodide version. */
  export const pyodideVersion: string
  /** The Pyodide runtime's directory, relative to the site's base URL. */
  export const pyodideDir: string
  /** alphareader-core.<hash>.zip, relative to the site's base URL. */
  export const coreBundle: string
  /** Packages loaded into Pyodide. */
  export const packages: readonly string[]
  /** Uncompressed bytes each boot stage downloads. */
  export const stageBytes: Record<'runtime' | 'numpy' | 'core', number>
  /** What the first import downloads, gzipped. */
  export const downloadBytes: number
}
